project:
  type: website
  output-dir: docs

website:
  title: "Your Name"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: shorts.qmd
        text: Shorts
      - href: publications.qmd
        text: Publications
    right:
      - icon: github
        href: https://github.com/edreiyu
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: article
