project:
  type: website
  output-dir: docs

website:
  title: "Edrei Yu"
  navbar:
  logo: assets/logo sample.jpg
  tools:
    - icon: github
      href: https://www.github.com/edreiyu
      aria-label: GitHub
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: shorts.qmd
        text: Shorts
      - href: publications.qmd
        text: Publications
  #  right:
  #    - icon: github
  #      href: https://github.com/edreiyu
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: article
